---
title: "stock_EDA_and_visualization"
output: html_document
date: "2025-10-30"
---

## R Markdown 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(tidyverse)
library(readr)
library(dplyr)
library(stringr)
library(purrr)
library(tidyquant)
library(lubridate)
```

# Loading Data
```{r}
data_path <- "data/"

all_files <- list.files(path = data_path,
                      pattern = "*.csv",
                      full.names = TRUE)
#seeing if files were found
print("--- Checking for files... ---")
if (length(all_files) == 0) {
  print("No .csv files were found in the 'data/' folder.")
} else {
  print("Found the following files:")
  print(all_files)
  
  all_stocks_df <- all_files %>%
    set_names(.) %>%
    map_dfr(read_csv, .id = "Stock") %>%
    
    mutate(Stock = str_remove(Stock, data_path),
           Stock = str_remove(Stock, ".csv"))

  print("--- Data successfully loaded! ---")
  print(head(all_stocks_df))
}
```

# Checking for missing values
```{r}
print(paste("Total missing values:", sum(is.na(all_stocks_df))))

# Start and end dates for EACH stock
date_ranges <- all_stocks_df %>%
  group_by(Stock) %>%
  summarize(
    StartDate = min(Date),
    EndDate = max(Date),
    TotalDays = n()
  ) %>%
  arrange(StartDate)

print("--- Date Ranges by Stock ---")
print(date_ranges)
```

```{r}
# Calculates daily % return for every stock

all_returns_df <- all_stocks_df %>%
  group_by(Stock) %>%
  tq_mutate(
    select     = Close,            
    mutate_fun = periodReturn,     
    period     = "daily",          
    col_rename = "Daily.Return"   
  ) %>%
  ungroup() %>%
  na.omit() 

print(head(all_returns_df))
```




